version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 183631306266.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo Adding execute permissions to gradlew...
      - chmod +x ./gradlew  # 실행 권한 추가
  build:
    commands:
      - echo Build started on `date`
      - echo Building the JAR file without tests...
      - ./gradlew build -x test  # 테스트를 건너뛰고 빌드
      - echo Building the Docker image...
      - docker build -t 183631306266.dkr.ecr.ap-southeast-1.amazonaws.com/yjs-todo-backend:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 183631306266.dkr.ecr.ap-southeast-1.amazonaws.com/yjs-todo-backend:latest
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"yjs-todo-backend","imageUri":"%s"}]' 183631306266.dkr.ecr.ap-southeast-1.amazonaws.com/yjs-todo-backend:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
