spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:*}"

jwt:
  secret: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey
  expirationMs: 86400000
